=== 2694831455/CrawlerArtifact/crawler-1-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT configuration (settings?,properties?,mappers?)>
<!ELEMENT properties (property+)>
<!ELEMENT settings (log?, cache?)>
<!ELEMENT mappers (mapper*,pack*)>
<!ELEMENT property (#PCDATA)>
<!ELEMENT log (#PCDATA)>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT mapper (#PCDATA)>
<!ELEMENT pack (#PCDATA)>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ATTLIST log
type CDATA #REQUIRED
level CDATA #REQUIRED
>
<!ATTLIST cache
timeout CDATA #REQUIRED
>
<!ATTLIST mapper
resource CDATA #REQUIRED
>
<!ATTLIST pack
value CDATA #REQUIRED
>

=== 2694831455/CrawlerArtifact/target/test-classes/crawler-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE configuration SYSTEM "crawler-1-config.dtd">

<configuration>

	<settings>
		<log type="log4j" level="info" />
		<cache timeout="300" />
	</settings>

	<properties>
		<property name="connectionTimeout" value="30000" />
		<property name="socketTimeout" value="30000" />
		<property name="maxConnectionsPerHost" value="200" />
		<property name="maxTotalConnections" value="200" />
	</properties>

	<mappers>
		<pack value="mappers/" />
	</mappers>

</configuration>
