=== 2694831455/CrawlerArtifact/src/main/java/com/crawler/artifact/builder/xml/crawler-1-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT mapper (globalheaders*,charset?,settings?,proxy?,schedule*, get*,post*,options*,delete*,head*,put*)>
<!ELEMENT settings (cache?)>
<!ELEMENT get (url*,charset?,headers?,retry?, properties*)>
<!ELEMENT post (url*,charset?,headers?,params?,retry?, properties*)>
<!ELEMENT delete (url*,charset?,headers?,params?,retry?, properties*)>
<!ELEMENT head (url*,charset?,headers?,params?,retry?, properties*)>
<!ELEMENT put (url*,charset?,headers?,params?,retry?, properties*)>
<!ELEMENT options (url*,charset?,headers?,params?,retry?, properties*)>
<!ELEMENT headers (header*)>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT schedule (#PCDATA)>
<!ELEMENT retry (times, means*, re-proxy?)>
<!ELEMENT globalheaders (header+)>
<!ELEMENT params (param+)>
<!ELEMENT properties (property*)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT times (#PCDATA)>
<!ELEMENT re-proxy (#PCDATA)>
<!ELEMENT means (mean+)>
<!ELEMENT mean (#PCDATA)>
<!ELEMENT proxy (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ELEMENT property (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT charset (#PCDATA)>
<!ATTLIST headers
refid CDATA #IMPLIED
>
<!ATTLIST header
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ATTLIST cache
timeout CDATA #REQUIRED
>
<!ATTLIST times
value CDATA #REQUIRED
>
<!ATTLIST mean
type CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ATTLIST proxy
serviceType CDATA #REQUIRED
fcType CDATA #REQUIRED
strategy CDATA #REQUIRED
>
<!ATTLIST globalheaders
id CDATA #REQUIRED
>
<!ATTLIST param
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ATTLIST properties
resume CDATA #IMPLIED
>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>
<!ATTLIST schedule
id CDATA #REQUIRED
location CDATA #REQUIRED
threadnum CDATA #IMPLIED
timeout CDATA #IMPLIED
>
<!ATTLIST get
id CDATA #REQUIRED
>
<!ATTLIST post
id CDATA #REQUIRED
>
<!ATTLIST options
id CDATA #REQUIRED
>
<!ATTLIST delete
id CDATA #REQUIRED
>
<!ATTLIST put
id CDATA #REQUIRED
>
<!ATTLIST head
id CDATA #REQUIRED
>
<!ATTLIST mapper
namespace CDATA #REQUIRED
crawlertype CDATA #IMPLIED
>
<!ATTLIST url
value CDATA #REQUIRED
>

=== 2694831455/CrawlerArtifact/src/test/resources/mappers/JdMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper SYSTEM "crawler-1-mapper.dtd" >
<mapper namespace="com.crawler.artifact.mappers.JdMapper">

	<globalheaders id="jdheaders">
		<header name="Host" value="www.jd.com" />
		<header name="User-Agent" value="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" />
		<header name="Accept" value="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" />
		<header name="Accept-Encoding" value="gzip, deflate" />
		<header name="Accept-Language" value="zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3" />
		<header name="Connection" value="keep-alive" />
		<header name="Upgrade-Insecure-Requests" value="1" />
	</globalheaders>

	<charset>utf-8</charset>

	<settings>
		<cache timeout="300" />
	</settings>

	<get id="jd_login">
		<headers refid="jdheaders" />
	</get>

</mapper>

=== 2694831455/CrawlerArtifact/src/test/resources/mappers/tbMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper SYSTEM "crawler-1-mapper.dtd" >
<mapper namespace="com.crawler.artifact.mappers.TbMapper">

	<globalheaders id="tbheaders">
		<header name="Host" value="www.jd.com" />
		<header name="User-Agent" value="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0" />
		<header name="Accept" value="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" />
		<header name="Accept-Encoding" value="gzip, deflate" />
		<header name="Accept-Language" value="zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3" />
		<header name="Connection" value="keep-alive" />
		<header name="Upgrade-Insecure-Requests" value="1" />
	</globalheaders>

	<charset>utf-8</charset>

	<settings>
		<cache timeout="300" />
	</settings>

	<get id="login">
		<url value="https://www.taobao.com/" />
		<headers refid="tbheaders" />
		<retry>
			<times value="3" />
			<means>
				<mean type="code" value="200" />
				<mean type="content" value="NamePlace" />
				<mean type="cookie" value="CoreSessionId" />
			</means>
		</retry>
		<properties resume="true">
			<property name="connectionTimeout" value="20000" />
			<property name="socketTimeout" value="20000" />
		</properties>
	</get>

</mapper>
